---
title: "diff_DESeq2"
output: html_document
---

```{r}
## Setup
### Bioconductor and CRAN libraries used
library(tidyverse)
library(RColorBrewer)
library(DESeq2)
library(pheatmap)
library(DEGreport)
library(factoextra)
```


```{r}
raw_counts <- read.table("../data/transcript_count_matrix.csv", header=T, row.names=1,sep = ",") 

# filter out count rows with either fewer than 10 counts or over 4000 counts
filt_sel = rowSums(raw_counts[,1:10]>=10)>0
raw_counts = raw_counts[filt_sel,]
dim(raw_counts)
filt_sel = rowSums(raw_counts[,1:10]<4000)>0
raw_counts = raw_counts[filt_sel,]
dim(raw_counts)
```

```{r}
sample_anno = read.csv("../data/sample_name_Aurelia.csv",header = FALSE,stringsAsFactors = FALSE)
colnames(raw_counts) = as.character(rev(sample_anno$V4))
metadata = read.table("../data/metadata.txt", header=T, row.names=1,sep = ",") 
```

```{r}
all(colnames(raw_counts) == rownames(metadata))
dds <- DESeqDataSetFromMatrix(countData = raw_counts, colData = metadata, design = ~ treatment)
```
```{r}
rld <- rlog(dds, blind=TRUE)
```

```{r}
plotPCA(rld, intgroup="regeneration")
plotPCA(rld, intgroup="treatment")
```


```{r}
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)
pheatmap(rld_cor)
```

```{r}
dds <- DESeq(dds)
normalized_counts <- counts(dds, normalized=TRUE)
write.csv(normalized_counts,file = "../data/normalized_counts.csv")
```

```{r}
plotDispEsts(dds)
```

## Set the comparison groups
```{r}
dds <- DESeqDataSetFromMatrix(countData = raw_counts, colData = metadata, design = ~ amputation)
rld <- rlog(dds, blind=TRUE)
dds <- DESeq(dds)
#amputation VA pre-amputation
contrast.ampu = c("amputation", "amputated", "pre_amputated")
# Output results of Wald test for contrast
res.ampu <- results(dds, contrast = contrast.ampu)
### Set thresholds
padj.cutoff <- 0.05
lfc.cutoff <- 0.58
res.ampu.tb <- res.ampu %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
res.ampu.sig <- res.ampu.tb %>%
        dplyr::filter(padj < padj.cutoff & abs(log2FoldChange) > lfc.cutoff)
res.ampu.sig
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = raw_counts, colData = metadata, design = ~regeneration)
rld <- rlog(dds, blind=TRUE)
dds <- DESeq(dds)
#amputation VA pre-amputation
contrast.rege = c("regeneration", "excited", "non_excited")
# Output results of Wald test for contrast
res.rege <- results(dds, contrast = contrast.rege)
### Set thresholds
padj.cutoff <- 0.05
lfc.cutoff <- 0.58
res.rege.tb <- res.rege %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
res.rege.sig <- res.rege.tb %>%
        dplyr::filter(padj < padj.cutoff & abs(log2FoldChange) > lfc.cutoff)
res.rege.sig
```

```{r}
plotMA(res.ampu, ylim=c(-3,3))
plotMA(res.rege, ylim=c(-3,3))
```

### Add annotation to Mus musculus genes
```{r}
blastx_anno = read.csv("../out/blastx_aurelia_mus.txt",sep = "\t",header = TRUE,stringsAsFactors = FALSE)
# keep only the first one for each of the query entry (lowest e-value)
blastx_anno = blastx_anno %>% group_by(query.acc.ver) %>% slice(1)

head(res.rege.sig)
add_mus_anno = function(df,by_left = "gene",out.name) {
  df_merged = merge(df,blastx_anno,by.x = by_left,by.y = "query.acc.ver")
  df_merged_anno = dplyr::select(df_merged,c(by_left,"log2FoldChange","padj","subject.acc.ver","evalue")) 
  write.csv(df_merged_anno,file = out.name,quote = FALSE)
}


add_mus_anno(res.rege.sig,"gene","../out/210205/res.rege.sig.csv")
add_mus_anno(res.ampu.sig,"gene","../out/210205/res.ampu.sig.csv")

```


```{r}
res.rege.sig.up = res.rege.sig %>% dplyr::filter(log2FoldChange>0) %>% arrange(desc(log2FoldChange))
res.rege.sig.do = res.rege.sig %>% dplyr::filter(log2FoldChange<0) %>% arrange(desc(log2FoldChange))
```

```{r}
res.ampu.sig.up = res.ampu.sig %>% dplyr::filter(log2FoldChange>0) %>% arrange(desc(log2FoldChange))
res.ampu.sig.do = res.ampu.sig %>% dplyr::filter(log2FoldChange<0) %>% arrange(desc(log2FoldChange))
```

```{r}
add_mus_anno(res.rege.sig.up,"gene","../out/210205/res.rege.sig.up.csv")
add_mus_anno(res.rege.sig.do,"gene","../out/210205/res.rege.sig.do.csv")
add_mus_anno(res.ampu.sig.up,"gene","../out/210205/res.ampu.sig.up.csv")
add_mus_anno(res.ampu.sig.do,"gene","../out/210205/res.ampu.sig.do.csv")
```

